@startuml createTask Controller activity
start
:Receive request and user ID from router;
if (check if name or completed in body is empty?) then (yes)
    :Response status code: 400 (Bad Request);
    :Send Error: "Invalid task data";
else (no)
    if (Task Inserted to MongoDB Successfully?) then (yes)
        :Response: "201 Created"
        :Send Message: "Task created" ;
    else (no)
        :Response: "500 Internal Server Error"
        :Send Error: "Cannot create task" ;
    endif
endif
stop
@enduml
