@startuml diagram router register
start
:Receive request; 
if (check url = "/register") then (no) 
    :Response status code: error 404(not found);
    else (yes) 
        if (method = "POST"?) then (no)
            :Response status code: error 405(method is not correct);
                else (yes) 
                    :Call function register of usre controller;
                    :Controller response to browser;
        endif
endif
stop
@enduml