@startuml diagram router createTask 
start
:Receive request; 
if (check url = "/createTask" and method = "POST"?) then (no)
    :Response status code: error 404(not found);
else (yes)
    :Call function createTask of controller;
    :Controller response to browser;
endif
stop
@enduml